#spring.h2.console.enabled=true
#spring.h2.console.path=/console
#spring.datasource.url=jdbc:h2:file:C:/Users/radek/Dysk Google/Projekty/28. Java developer/IdeaProjects/todo-app/todo-db
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.password=sa
#spring.datasource.username=sa

#spring.datasource.url=jdbc:mysql://localhost:3306/todo_db?serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=create

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/todo_db?serverTimezone=UTC'
    username: 'root'
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: validate

